name: Rust
on:
  push:
    branches: [ "develop", "github" ]
  pull_request:
    branches: [ "develop", "github" ]
#on:
#  push:
#    tags:
#    - 'v*'

env:
  CARGO_TERM_COLOR: always
  REPO_NAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v3
    - name: echo REPO_NAME
      run: echo ${{ env.REPO_NAME }}
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        profile: minimal
        override: true
        target: ${{ matrix.target }}
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}
    - name: list all files
      run: find target/
    - name: Gzip aritfacts
      run: gzip -c target/${{ matrix.target }}/release/${{ env.REPO_NAME }} > target/${{ env.REPO_NAME }}.${{ matrix.target }}.gz
    - name: Upload aritfacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          target/${{ env.REPO_NAME }}.*.gz
    - name: List Builds
      run: ls -l target/
    - name: Release
      uses: softprops/action-gh-release@v1                         # https://github.com/softprops/action-gh-release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        prerelease: true
        files: |
          target/${{ env.REPO_NAME }}.*.gz
